Repository jenkins-infra/docker-packaging, pull requests merged in 2022-01, with the labels that each got.

#21 fix: switch linux packaging to single-container JNLP
  Dockerfile
Labels: enhancement, breaking, dependencies

#22 feat: add JDK8 and use it as default
  .dockerignore
  Dockerfile
Labels: enhancement

#24 Install additional packages
  Dockerfile
Labels: enhancement

#25 Use a UTF-8 locale
  Dockerfile
Labels: bug

#27 fix: add (default)jdk bin to the path
  Dockerfile
Labels: bug

#29 Add systemd RPM macros
  Dockerfile
  macros.d/macros.systemd
Labels: enhancement

#31 Use even older macros
  macros.d/macros.systemd
Labels: enhancement
