Repository jenkins-infra/docker-packaging, pull requests merged in 2024-06, with the labels that each got.

#111 chore(updatecli) Track Maven version.
  updatecli/updatecli.d/maven.yaml
Labels: chore, updatecli, maven

#116 chore(Dockerfile) use ARG to specify the JDK major versions.
  Dockerfile
Labels: chore

#123 Use correct documentation hyperlink to release repository
  README.adoc
Labels: documentation

#124 feat(docker): compile for both amd64 and arm64
  Jenkinsfile_k8s
Labels: enhancement
